platform :ios, '10.0'

target 'GoogleAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleAPI
  pod 'GoogleSignIn'
  pod 'Fakery'
  pod 'SpreadsheetView'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'FirebaseAuth'
  pod 'Firebase/Storage'
  pod 'SnapKit', '~> 5.0.0'
end
